// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 3beb4722ca
// Version Date: 2019年10月24日 星期四 23时47分48秒 UTC

package main

import (
	"flag"

	// This Service
	"github.com/metaverse/truss/_example/skappservice-service/svc/server"
)

func main() {
	// Update addresses if they have been overwritten by flags
	flag.Parse()

	server.Run(server.DefaultConfig)
}
