// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 3beb4722ca
// Version Date: 2019年10月24日 星期四 23时47分48秒 UTC

// Package http provides an HTTP client for the SkAppService service.
package http

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"net/url"
	"strings"

	"github.com/gogo/protobuf/jsonpb"

	"github.com/go-kit/kit/endpoint"
	httptransport "github.com/go-kit/kit/transport/http"
	"github.com/pkg/errors"

	// This Service
	pb "github.com/metaverse/truss/_example"
	"github.com/metaverse/truss/_example/skappservice-service/svc"
)

var (
	_ = endpoint.Chain
	_ = httptransport.NewClient
	_ = fmt.Sprint
	_ = bytes.Compare
	_ = ioutil.NopCloser
)

// New returns a service backed by an HTTP server living at the remote
// instance. We expect instance to come from a service discovery system, so
// likely of the form "host:port".
func New(instance string, options ...httptransport.ClientOption) (pb.SkAppServiceServer, error) {

	if !strings.HasPrefix(instance, "http") {
		instance = "http://" + instance
	}
	u, err := url.Parse(instance)
	if err != nil {
		return nil, err
	}
	_ = u

	var SeckillZeroEndpoint endpoint.Endpoint
	{
		SeckillZeroEndpoint = httptransport.NewClient(
			"POST",
			copyURL(u, "/sec/"),
			EncodeHTTPSeckillZeroRequest,
			DecodeHTTPSeckillResponse,
			options...,
		).Endpoint()
	}
	var SecInfoZeroEndpoint endpoint.Endpoint
	{
		SecInfoZeroEndpoint = httptransport.NewClient(
			"GET",
			copyURL(u, "/sec/info"),
			EncodeHTTPSecInfoZeroRequest,
			DecodeHTTPSecInfoResponse,
			options...,
		).Endpoint()
	}
	var SecInfoListZeroEndpoint endpoint.Endpoint
	{
		SecInfoListZeroEndpoint = httptransport.NewClient(
			"GET",
			copyURL(u, "/sec/list"),
			EncodeHTTPSecInfoListZeroRequest,
			DecodeHTTPSecInfoListResponse,
			options...,
		).Endpoint()
	}

	return svc.Endpoints{
		SeckillEndpoint:     SeckillZeroEndpoint,
		SecInfoEndpoint:     SecInfoZeroEndpoint,
		SecInfoListEndpoint: SecInfoListZeroEndpoint,
	}, nil
}

func copyURL(base *url.URL, path string) *url.URL {
	next := *base
	next.Path = path
	return &next
}

// CtxValuesToSend configures the http client to pull the specified keys out of
// the context and add them to the http request as headers.  Note that keys
// will have net/http.CanonicalHeaderKey called on them before being send over
// the wire and that is the form they will be available in the server context.
func CtxValuesToSend(keys ...string) httptransport.ClientOption {
	return httptransport.ClientBefore(func(ctx context.Context, r *http.Request) context.Context {
		for _, k := range keys {
			if v, ok := ctx.Value(k).(string); ok {
				r.Header.Set(k, v)
			}
		}
		return ctx
	})
}

// HTTP Client Decode

// DecodeHTTPSeckillResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded SecResponse response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPSeckillResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.SecResponse
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// DecodeHTTPSecInfoResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded SecInfoResponse response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPSecInfoResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.SecInfoResponse
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// DecodeHTTPSecInfoListResponse is a transport/http.DecodeResponseFunc that decodes
// a JSON-encoded SecInfoListResponse response from the HTTP response body.
// If the response has a non-200 status code, we will interpret that as an
// error and attempt to decode the specific error message from the response
// body. Primarily useful in a client.
func DecodeHTTPSecInfoListResponse(_ context.Context, r *http.Response) (interface{}, error) {
	defer r.Body.Close()
	buf, err := ioutil.ReadAll(r.Body)
	if err == io.EOF {
		return nil, errors.New("response http body empty")
	}
	if err != nil {
		return nil, errors.Wrap(err, "cannot read http body")
	}

	if r.StatusCode != http.StatusOK {
		return nil, errors.Wrapf(errorDecoder(buf), "status code: '%d'", r.StatusCode)
	}

	var resp pb.SecInfoListResponse
	if err = jsonpb.UnmarshalString(string(buf), &resp); err != nil {
		return nil, errorDecoder(buf)
	}

	return &resp, nil
}

// HTTP Client Encode

// EncodeHTTPSeckillZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a seckill request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPSeckillZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.SecRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"sec",
		"",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("ProductId", fmt.Sprint(req.ProductId))

	values.Add("Source", fmt.Sprint(req.Source))

	values.Add("AuthCode", fmt.Sprint(req.AuthCode))

	values.Add("SecTime", fmt.Sprint(req.SecTime))

	values.Add("Nance", fmt.Sprint(req.Nance))

	values.Add("UserId", fmt.Sprint(req.UserId))

	values.Add("UserAuthSign", fmt.Sprint(req.UserAuthSign))

	values.Add("ClientAddr", fmt.Sprint(req.ClientAddr))

	values.Add("ClientRefence", fmt.Sprint(req.ClientRefence))

	r.URL.RawQuery = values.Encode()
	// Set the body parameters
	var buf bytes.Buffer
	toRet := request.(*pb.SecRequest)
	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(toRet); err != nil {
		return errors.Wrapf(err, "couldn't encode body as json %v", toRet)
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}

// EncodeHTTPSeckillOneRequest is a transport/http.EncodeRequestFunc
// that encodes a seckill request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPSeckillOneRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.SecRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"sec",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("ProductId", fmt.Sprint(req.ProductId))

	values.Add("Source", fmt.Sprint(req.Source))

	values.Add("AuthCode", fmt.Sprint(req.AuthCode))

	values.Add("SecTime", fmt.Sprint(req.SecTime))

	values.Add("Nance", fmt.Sprint(req.Nance))

	values.Add("UserId", fmt.Sprint(req.UserId))

	values.Add("UserAuthSign", fmt.Sprint(req.UserAuthSign))

	values.Add("ClientAddr", fmt.Sprint(req.ClientAddr))

	values.Add("ClientRefence", fmt.Sprint(req.ClientRefence))

	r.URL.RawQuery = values.Encode()
	// Set the body parameters
	var buf bytes.Buffer
	toRet := request.(*pb.SecRequest)
	encoder := json.NewEncoder(&buf)
	encoder.SetEscapeHTML(false)
	if err := encoder.Encode(toRet); err != nil {
		return errors.Wrapf(err, "couldn't encode body as json %v", toRet)
	}
	r.Body = ioutil.NopCloser(&buf)
	return nil
}

// EncodeHTTPSecInfoZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a secinfo request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPSecInfoZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.SecInfoRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"sec",
		"info",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("productId", fmt.Sprint(req.ProductId))

	r.URL.RawQuery = values.Encode()
	return nil
}

// EncodeHTTPSecInfoOneRequest is a transport/http.EncodeRequestFunc
// that encodes a secinfo request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPSecInfoOneRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.SecInfoRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"sec",
		"info",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("productId", fmt.Sprint(req.ProductId))

	r.URL.RawQuery = values.Encode()
	return nil
}

// EncodeHTTPSecInfoListZeroRequest is a transport/http.EncodeRequestFunc
// that encodes a secinfolist request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPSecInfoListZeroRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.SecInfoListRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"sec",
		"list",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("Out", fmt.Sprint(req.Out))

	r.URL.RawQuery = values.Encode()
	return nil
}

// EncodeHTTPSecInfoListOneRequest is a transport/http.EncodeRequestFunc
// that encodes a secinfolist request into the various portions of
// the http request (path, query, and body).
func EncodeHTTPSecInfoListOneRequest(_ context.Context, r *http.Request, request interface{}) error {
	strval := ""
	_ = strval
	req := request.(*pb.SecInfoListRequest)
	_ = req

	r.Header.Set("transport", "HTTPJSON")
	r.Header.Set("request-url", r.URL.Path)

	// Set the path parameters
	path := strings.Join([]string{
		"",
		"sec",
		"list",
	}, "/")
	u, err := url.Parse(path)
	if err != nil {
		return errors.Wrapf(err, "couldn't unmarshal path %q", path)
	}
	r.URL.RawPath = u.RawPath
	r.URL.Path = u.Path

	// Set the query parameters
	values := r.URL.Query()
	var tmp []byte
	_ = tmp

	values.Add("Out", fmt.Sprint(req.Out))

	r.URL.RawQuery = values.Encode()
	return nil
}

func errorDecoder(buf []byte) error {
	var w errorWrapper
	if err := json.Unmarshal(buf, &w); err != nil {
		const size = 8196
		if len(buf) > size {
			buf = buf[:size]
		}
		return fmt.Errorf("response body '%s': cannot parse non-json request body", buf)
	}

	return errors.New(w.Error)
}

type errorWrapper struct {
	Error string `json:"error"`
}
