// Code generated by truss. DO NOT EDIT.
// Rerunning truss will overwrite this file.
// Version: 3beb4722ca
// Version Date: 2019年10月24日 星期四 23时47分48秒 UTC

package svc

// This file provides server-side bindings for the HTTP transport.
// It utilizes the transport/http.Server.

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"io/ioutil"
	"net/http"
	"strconv"
	"strings"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"

	"context"

	httptransport "github.com/go-kit/kit/transport/http"
	"github.com/gorilla/mux"
	"github.com/pkg/errors"

	// This service
	pb "github.com/metaverse/truss/_example"
)

const contentType = "application/json; charset=utf-8"

var (
	_ = fmt.Sprint
	_ = bytes.Compare
	_ = strconv.Atoi
	_ = httptransport.NewServer
	_ = ioutil.NopCloser
	_ = pb.NewSkAppServiceClient
	_ = io.Copy
	_ = errors.Wrap
)

// MakeHTTPHandler returns a handler that makes a set of endpoints available
// on predefined paths.
func MakeHTTPHandler(endpoints Endpoints) http.Handler {
	serverOptions := []httptransport.ServerOption{
		httptransport.ServerBefore(headersToContext),
		httptransport.ServerErrorEncoder(errorEncoder),
		httptransport.ServerAfter(httptransport.SetContentType(contentType)),
	}
	m := mux.NewRouter()

	m.Methods("POST").Path("/sec/").Handler(httptransport.NewServer(
		endpoints.SeckillEndpoint,
		DecodeHTTPSeckillZeroRequest,
		EncodeHTTPGenericResponse,
		serverOptions...,
	))
	m.Methods("POST").Path("/sec").Handler(httptransport.NewServer(
		endpoints.SeckillEndpoint,
		DecodeHTTPSeckillOneRequest,
		EncodeHTTPGenericResponse,
		serverOptions...,
	))

	m.Methods("GET").Path("/sec/info").Handler(httptransport.NewServer(
		endpoints.SecInfoEndpoint,
		DecodeHTTPSecInfoZeroRequest,
		EncodeHTTPGenericResponse,
		serverOptions...,
	))
	m.Methods("GET").Path("/sec/info").Handler(httptransport.NewServer(
		endpoints.SecInfoEndpoint,
		DecodeHTTPSecInfoOneRequest,
		EncodeHTTPGenericResponse,
		serverOptions...,
	))

	m.Methods("GET").Path("/sec/list").Handler(httptransport.NewServer(
		endpoints.SecInfoListEndpoint,
		DecodeHTTPSecInfoListZeroRequest,
		EncodeHTTPGenericResponse,
		serverOptions...,
	))
	m.Methods("GET").Path("/sec/list").Handler(httptransport.NewServer(
		endpoints.SecInfoListEndpoint,
		DecodeHTTPSecInfoListOneRequest,
		EncodeHTTPGenericResponse,
		serverOptions...,
	))
	return m
}

// ErrorEncoder writes the error to the ResponseWriter, by default a content
// type of application/json, a body of json with key "error" and the value
// error.Error(), and a status code of 500. If the error implements Headerer,
// the provided headers will be applied to the response. If the error
// implements json.Marshaler, and the marshaling succeeds, the JSON encoded
// form of the error will be used. If the error implements StatusCoder, the
// provided StatusCode will be used instead of 500.
func errorEncoder(_ context.Context, err error, w http.ResponseWriter) {
	body, _ := json.Marshal(errorWrapper{Error: err.Error()})
	if marshaler, ok := err.(json.Marshaler); ok {
		if jsonBody, marshalErr := marshaler.MarshalJSON(); marshalErr == nil {
			body = jsonBody
		}
	}
	w.Header().Set("Content-Type", contentType)
	if headerer, ok := err.(httptransport.Headerer); ok {
		for k := range headerer.Headers() {
			w.Header().Set(k, headerer.Headers().Get(k))
		}
	}
	code := http.StatusInternalServerError
	if sc, ok := err.(httptransport.StatusCoder); ok {
		code = sc.StatusCode()
	}
	w.WriteHeader(code)
	w.Write(body)
}

type errorWrapper struct {
	Error string `json:"error"`
}

// httpError satisfies the Headerer and StatusCoder interfaces in
// package github.com/go-kit/kit/transport/http.
type httpError struct {
	error
	statusCode int
	headers    map[string][]string
}

func (h httpError) StatusCode() int {
	return h.statusCode
}

func (h httpError) Headers() http.Header {
	return h.headers
}

// Server Decode

// DecodeHTTPSeckillZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded seckill request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPSeckillZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.SecRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{fmt.Errorf("request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	if ProductIdSeckillStrArr, ok := queryParams["ProductId"]; ok {
		ProductIdSeckillStr := ProductIdSeckillStrArr[0]
		ProductIdSeckill, err := strconv.ParseInt(ProductIdSeckillStr, 10, 32)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting ProductIdSeckill from query, queryParams: %v", queryParams))
		}
		req.ProductId = int32(ProductIdSeckill)
	}

	if SourceSeckillStrArr, ok := queryParams["Source"]; ok {
		SourceSeckillStr := SourceSeckillStrArr[0]
		SourceSeckill := SourceSeckillStr
		req.Source = SourceSeckill
	}

	if AuthCodeSeckillStrArr, ok := queryParams["AuthCode"]; ok {
		AuthCodeSeckillStr := AuthCodeSeckillStrArr[0]
		AuthCodeSeckill := AuthCodeSeckillStr
		req.AuthCode = AuthCodeSeckill
	}

	if SecTimeSeckillStrArr, ok := queryParams["SecTime"]; ok {
		SecTimeSeckillStr := SecTimeSeckillStrArr[0]
		SecTimeSeckill, err := strconv.ParseInt(SecTimeSeckillStr, 10, 64)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting SecTimeSeckill from query, queryParams: %v", queryParams))
		}
		req.SecTime = SecTimeSeckill
	}

	if NanceSeckillStrArr, ok := queryParams["Nance"]; ok {
		NanceSeckillStr := NanceSeckillStrArr[0]
		NanceSeckill := NanceSeckillStr
		req.Nance = NanceSeckill
	}

	if UserIdSeckillStrArr, ok := queryParams["UserId"]; ok {
		UserIdSeckillStr := UserIdSeckillStrArr[0]
		UserIdSeckill, err := strconv.ParseInt(UserIdSeckillStr, 10, 32)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting UserIdSeckill from query, queryParams: %v", queryParams))
		}
		req.UserId = int32(UserIdSeckill)
	}

	if UserAuthSignSeckillStrArr, ok := queryParams["UserAuthSign"]; ok {
		UserAuthSignSeckillStr := UserAuthSignSeckillStrArr[0]
		UserAuthSignSeckill := UserAuthSignSeckillStr
		req.UserAuthSign = UserAuthSignSeckill
	}

	if ClientAddrSeckillStrArr, ok := queryParams["ClientAddr"]; ok {
		ClientAddrSeckillStr := ClientAddrSeckillStrArr[0]
		ClientAddrSeckill := ClientAddrSeckillStr
		req.ClientAddr = ClientAddrSeckill
	}

	if ClientRefenceSeckillStrArr, ok := queryParams["ClientRefence"]; ok {
		ClientRefenceSeckillStr := ClientRefenceSeckillStrArr[0]
		ClientRefenceSeckill := ClientRefenceSeckillStr
		req.ClientRefence = ClientRefenceSeckill
	}

	return &req, err
}

// DecodeHTTPSeckillOneRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded seckill request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPSeckillOneRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.SecRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{fmt.Errorf("request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	if ProductIdSeckillStrArr, ok := queryParams["ProductId"]; ok {
		ProductIdSeckillStr := ProductIdSeckillStrArr[0]
		ProductIdSeckill, err := strconv.ParseInt(ProductIdSeckillStr, 10, 32)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting ProductIdSeckill from query, queryParams: %v", queryParams))
		}
		req.ProductId = int32(ProductIdSeckill)
	}

	if SourceSeckillStrArr, ok := queryParams["Source"]; ok {
		SourceSeckillStr := SourceSeckillStrArr[0]
		SourceSeckill := SourceSeckillStr
		req.Source = SourceSeckill
	}

	if AuthCodeSeckillStrArr, ok := queryParams["AuthCode"]; ok {
		AuthCodeSeckillStr := AuthCodeSeckillStrArr[0]
		AuthCodeSeckill := AuthCodeSeckillStr
		req.AuthCode = AuthCodeSeckill
	}

	if SecTimeSeckillStrArr, ok := queryParams["SecTime"]; ok {
		SecTimeSeckillStr := SecTimeSeckillStrArr[0]
		SecTimeSeckill, err := strconv.ParseInt(SecTimeSeckillStr, 10, 64)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting SecTimeSeckill from query, queryParams: %v", queryParams))
		}
		req.SecTime = SecTimeSeckill
	}

	if NanceSeckillStrArr, ok := queryParams["Nance"]; ok {
		NanceSeckillStr := NanceSeckillStrArr[0]
		NanceSeckill := NanceSeckillStr
		req.Nance = NanceSeckill
	}

	if UserIdSeckillStrArr, ok := queryParams["UserId"]; ok {
		UserIdSeckillStr := UserIdSeckillStrArr[0]
		UserIdSeckill, err := strconv.ParseInt(UserIdSeckillStr, 10, 32)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting UserIdSeckill from query, queryParams: %v", queryParams))
		}
		req.UserId = int32(UserIdSeckill)
	}

	if UserAuthSignSeckillStrArr, ok := queryParams["UserAuthSign"]; ok {
		UserAuthSignSeckillStr := UserAuthSignSeckillStrArr[0]
		UserAuthSignSeckill := UserAuthSignSeckillStr
		req.UserAuthSign = UserAuthSignSeckill
	}

	if ClientAddrSeckillStrArr, ok := queryParams["ClientAddr"]; ok {
		ClientAddrSeckillStr := ClientAddrSeckillStrArr[0]
		ClientAddrSeckill := ClientAddrSeckillStr
		req.ClientAddr = ClientAddrSeckill
	}

	if ClientRefenceSeckillStrArr, ok := queryParams["ClientRefence"]; ok {
		ClientRefenceSeckillStr := ClientRefenceSeckillStrArr[0]
		ClientRefenceSeckill := ClientRefenceSeckillStr
		req.ClientRefence = ClientRefenceSeckill
	}

	return &req, err
}

// DecodeHTTPSecInfoZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded secinfo request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPSecInfoZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.SecInfoRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{fmt.Errorf("request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	if ProductIdSecInfoStrArr, ok := queryParams["productId"]; ok {
		ProductIdSecInfoStr := ProductIdSecInfoStrArr[0]
		ProductIdSecInfo, err := strconv.ParseInt(ProductIdSecInfoStr, 10, 32)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting ProductIdSecInfo from query, queryParams: %v", queryParams))
		}
		req.ProductId = int32(ProductIdSecInfo)
	}

	return &req, err
}

// DecodeHTTPSecInfoOneRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded secinfo request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPSecInfoOneRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.SecInfoRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{fmt.Errorf("request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	if ProductIdSecInfoStrArr, ok := queryParams["productId"]; ok {
		ProductIdSecInfoStr := ProductIdSecInfoStrArr[0]
		ProductIdSecInfo, err := strconv.ParseInt(ProductIdSecInfoStr, 10, 32)
		if err != nil {
			return nil, errors.Wrap(err, fmt.Sprintf("Error while extracting ProductIdSecInfo from query, queryParams: %v", queryParams))
		}
		req.ProductId = int32(ProductIdSecInfo)
	}

	return &req, err
}

// DecodeHTTPSecInfoListZeroRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded secinfolist request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPSecInfoListZeroRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.SecInfoListRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{fmt.Errorf("request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	if OutSecInfoListStrArr, ok := queryParams["Out"]; ok {
		OutSecInfoListStr := OutSecInfoListStrArr[0]
		OutSecInfoList := OutSecInfoListStr
		req.Out = OutSecInfoList
	}

	return &req, err
}

// DecodeHTTPSecInfoListOneRequest is a transport/http.DecodeRequestFunc that
// decodes a JSON-encoded secinfolist request from the HTTP request
// body. Primarily useful in a server.
func DecodeHTTPSecInfoListOneRequest(_ context.Context, r *http.Request) (interface{}, error) {
	defer r.Body.Close()
	var req pb.SecInfoListRequest
	buf, err := ioutil.ReadAll(r.Body)
	if err != nil {
		return nil, errors.Wrapf(err, "cannot read body of http request")
	}
	if len(buf) > 0 {
		// AllowUnknownFields stops the unmarshaler from failing if the JSON contains unknown fields.
		unmarshaller := jsonpb.Unmarshaler{
			AllowUnknownFields: true,
		}
		if err = unmarshaller.Unmarshal(bytes.NewBuffer(buf), &req); err != nil {
			const size = 8196
			if len(buf) > size {
				buf = buf[:size]
			}
			return nil, httpError{fmt.Errorf("request body '%s': cannot parse non-json request body", buf),
				http.StatusBadRequest,
				nil,
			}
		}
	}

	pathParams := mux.Vars(r)
	_ = pathParams

	queryParams := r.URL.Query()
	_ = queryParams

	if OutSecInfoListStrArr, ok := queryParams["Out"]; ok {
		OutSecInfoListStr := OutSecInfoListStrArr[0]
		OutSecInfoList := OutSecInfoListStr
		req.Out = OutSecInfoList
	}

	return &req, err
}

// EncodeHTTPGenericResponse is a transport/http.EncodeResponseFunc that encodes
// the response as JSON to the response writer. Primarily useful in a server.
func EncodeHTTPGenericResponse(_ context.Context, w http.ResponseWriter, response interface{}) error {
	marshaller := jsonpb.Marshaler{
		EmitDefaults: false,
		OrigName:     true,
	}

	return marshaller.Marshal(w, response.(proto.Message))
}

// Helper functions

func headersToContext(ctx context.Context, r *http.Request) context.Context {
	for k, _ := range r.Header {
		// The key is added both in http format (k) which has had
		// http.CanonicalHeaderKey called on it in transport as well as the
		// strings.ToLower which is the grpc metadata format of the key so
		// that it can be accessed in either format
		ctx = context.WithValue(ctx, k, r.Header.Get(k))
		ctx = context.WithValue(ctx, strings.ToLower(k), r.Header.Get(k))
	}

	// Tune specific change.
	// also add the request url
	ctx = context.WithValue(ctx, "request-url", r.URL.Path)
	ctx = context.WithValue(ctx, "transport", "HTTPJSON")

	return ctx
}
